path_openalex: './dataset/OpenAlex/'
path_pcs: './dataset/PCS/'
path_wos: './dataset/WOS/'
path_cnki: './dataset/CNKI/'
path_other: './dataset/Miscellaneous/'
path_csmar: './dataset/CSMAR_subsidiary/'
path_cnpat: './dataset/CN_patents/'
path_uspat: './dataset/US_patents/'
path_processed: './proc_output/'
path_stata: './stata_output/'
path_figure: './figure_output/'