def locate_entity(entry):
    from rapidfuzz import process, fuzz

    full_result =  {'china electronics technology group corporation 13th research institute': 2018,
                    'china electronics technology group corporation 38th research institute': 2018,
                    'china electronics technology group corporation 55th research institute': 2018,
                    'china volant industry': 2018,
                    'hebei far east communication system engineering': 2018,
                    'chengdu jiashi': 2018,
                    'chengdu hiwafer semiconductor': 2018,
                    'fujian jinhua integrated circuit': 2018,
                    'chengdu haiguang': 2019,
                    'huawei': 2019,
                    'dawning information': 2019,
                    'wuxi jiangnan institute of computing technology': 2019,
                    'china general nuclear power': 2019,
                    'china nuclear power technology': 2019,
                    'suzhou nuclear power': 2019,
                    'zhejiang dahua': 2019,
                    'hikvision': 2019,
                    'iflytek': 2019,
                    'megvii': 2019,
                    'sensetime': 2019,
                    'xiamen meiya pico': 2019,
                    'shanghai yitu': 2019,
                    'yixin science and tech': 2019,
                    'wuhan yiersen': 2020,
                    'beijing zhongyun rongxin': 2020,
                    'beijing jincheng hanyu': 2020,
                    'china jiuyuan': 2020,
                    'harbin chuangyue': 2020,
                    'harbin yunlida': 2020,
                    'qihoo 360': 2020,
                    'shanghai nova instruments': 2020,
                    'sichuan dingcheng': 2020,
                    'sichuan xintianyuan': 2020,
                    'sichuan tuske': 2020,
                    'lijian tianyan': 2020,
                    'kuaijisong': 2020,
                    'aksu huafu color spinning': 2020,
                    'cloudwalk': 2020,
                    'fiberhome': 2020,
                    'nanjing fenghuo starrysky': 2020,
                    'netposa technologies': 2020,
                    'sensenets': 2020,
                    'intellifusion technologies': 2020,
                    'easyway': 2020,
                    'bgi genomics': 2020,
                    'beijing genomics institute': 2020,
                    'changji esquel textile': 2020,
                    'hefei baolongda': 2020,
                    'hefei meiling': 2020,
                    'hetian haolin hair': 2020,
                    'hetian teda garments': 2020,
                    'jinchuang': 2020,
                    'nanjing xinyimian': 2020,
                    'nanchang o film': 2020,
                    'tanyuan technology': 2020,
                    'cccc dredging': 2020,
                    'cccc tianjin': 2020,
                    'cccc shanghai': 2020,
                    'cccc guangzhou': 2020,
                    'cccc second harbor engineering': 2020,
                    'beijing huanjia': 2020,
                    'changzhou guoguang': 2020,
                    'china electronics technology group corporation no 7 research institute': 2020,
                    'beijing chongxin bada': 2020,
                    'guangzhou guangyou': 2020,
                    'guangzhou haige': 2020,
                    'guilin changhai': 2020,
                    'hubei guangxing': 2020,
                    'shaanxi changling electronic': 2020,
                    'shanghai kaibo': 2020,
                    'beijing telixin electronic': 2020,
                    'tianjin broadcasting equipment': 2020,
                    'tianjin 764': 2020,
                    'wuhan mailet': 2020,
                    'wuxi zhongde meilian biotechnology': 2020,
                    'china communications construction company': 2020,
                    'cccc': 2020,
                    'china national scientific instruments and materials': 2020,
                    'chongqing chuandong shipbuilding': 2020,
                    'cssc huangpu wenchong': 2020,
                    'dji technology': 2020,
                    'guangxin maritime heavy': 2020,
                    'guangzhou taicheng shipbuilding': 2020,
                    'jiangsu hengxiang': 2020,
                    'shenzhen guangui': 2020,
                    'nanjing asset management': 2020,
                    'ningbo semiconductor': 2020,
                    'north microelectronics': 2020,
                    'semiconductor manufacturing international': 2020,
                    'smic': 2020,
                    'smic south integrated circuit': 2020,
                    'smic changdian semiconductor': 2020,
                    'smic holdings': 2020,
                    'smic northern integrated circuit': 2020,
                    'smic semiconductor': 2020,
                    'nuctech company': 2020,
                    'tsinghua tongfang': 2020,
                    'aero engine corporation of china': 2020,
                    'aecc': 2020,
                    'aecc power': 2020,
                    'aecc gas turbine': 2020,
                    'aecc commercial aircraft engine': 2020,
                    'aecc harbin dongan engine': 2020,
                    'aecc shenyang': 2020,
                    'aecc hunan': 2020,
                    'anhui yingliu aerospace power': 2020,
                    'aviation industry corporation of china': 2020,
                    'avic': 2020,
                    'avic aircraft': 2020,
                    'chengdu aircraft industry': 2020,
                    'avic general': 2020,
                    'zhejiang institute of avic': 2020,
                    'avic international': 2023,
                    'beijing baimu': 2020,
                    'beijing andatek': 2020,
                    'beijing liweier aviation': 2020,
                    'guangming yuanda electronics': 2020,
                    'xian aerospace propulsion': 2020,
                    'chengdu hangli aviation': 2020,
                    'avic aviation standard parts': 2020,
                    'cssc xigong': 2020,
                    'shanghai yiling electronic': 2020,
                    'hefei fuhua precision machinery': 2020,
                    'guangzhou hangxin': 2020,
                    'guizhou hanyu aviation': 2020,
                    'guizhou liyang international manufacturing': 2020,
                    'avic helicopter': 2020,
                    'hangzhou bearing test': 2020,
                    'harbin general aircraft': 2020,
                    'henan aerospace precision': 2020,
                    'hunan southern general': 2020,
                    'chongqing aoputai communication': 2020,
                    'jiangsu meilong': 2020,
                    'hubei hanyu jiatai': 2020,
                    'jincheng group': 2020,
                    'medix laboratory': 2020,
                    'shaanxi aero electrics': 2020,
                    'shaanxi aircraft industry': 2020,
                    'shanghai aerospace equipment': 2020,
                    'shanghai aircraft manufacturing': 2020,
                    'shanghai tianlang electronic': 2020,
                    'shenyang instrument science research': 2020,
                    'shenyang aircraft': 2020,
                    'neiyang xizi aviation': 2020,
                    'sichuan hangte aviation': 2020,
                    'chengtai aviation': 2020,
                    'jiangsu sumec instruments': 2020,
                    'suzhou yike': 2020,
                    'wuxi hanger': 2020,
                    'wuxi parker new material': 2020,
                    'wuxi turbine blade': 2020,
                    'xian aircraft industry avionics': 2020,
                    'xifei science   technology': 2020,
                    'aecc xian aero engine controls': 2020,
                    'xian aircraft industry': 2020,
                    'xian xihang group': 2020,
                    'xian xiluo aviation': 2020,
                    'yibin sanjiang machinery': 2020,
                    'zhejiang wanmei': 2020,
                    'china national offshore oil': 2021,
                    'cnooc': 2021,
                    'beijing tianjiao aviation': 2021,
                    'xinwei microelectronics': 2021,
                    'tianjin phytium': 2021,
                    'hoshine silicon': 2021,
                    'xinjiang daqo new energy': 2021,
                    'xinjiang eastern hope': 2021,
                    'xinjiang gcl new energy': 2021,
                    'beijing eastsoft junyue': 2021,
                    'beijing yanjing electronics': 2021,
                    'beijing geling shentong': 2021,
                    'beijing haili united': 2021,
                    'beijing zhongdian xingfa': 2021,
                    'chengdu xiwu xinan intelligent system': 2021,
                    'west infosec intelligent system': 2021,
                    'hangzhou hualan microelectronics': 2021,
                    'shanghai jinzhuo': 2021,
                    'beijing eastsoft': 2021,
                    'liang tech': 2021,
                    'shenzhen kepa information': 2021,
                    'shenzhen huaantai': 2021,
                    'suzhou keda': 2021,
                    'tongfang ruian': 2021,
                    'urumqi tianyao weiye': 2021,
                    'wuhan raycus fiber laser': 2021,
                    'xin zui beidou tongchuang': 2021,
                    'xinjiang lianhai chuangzhi': 2021,
                    'xinjiang xiling information': 2021,
                    'xinjiang tangli': 2021,
                    'shenzhen jiazhao': 2021,
                    'hangzhou zhongke microelectronics': 2021,
                    'hunan goke microelectronics': 2021,
                    'h3c semiconductor': 2021,
                    'poly asia pacific': 2021,
                    'quantumctek': 2021,
                    'shaanxi zhien electromechanical': 2021,
                    'shanghai guodun quantum': 2021,
                    'xian aerospace huaxun': 2021,
                    'suzhou yunxin microelectronics': 2021,
                    'aerospace zanguang': 2021,
                    'zhanguang': 2021,
                    'changsha jingjia microelectronics': 2021,
                    'kontel tech': 2021,
                    'fujian torch electronic': 2021,
                    'hangzhou hikvision': 2021,
                    'huahai communication': 2021,
                    'hong kong changhua electronics': 2021,
                    'huashijie electronics': 2021,
                    'hua vision electronics': 2021,
                    'super systems alliance': 2021,
                    'inner mongolia first machinery': 2021,
                    'jiangsu hengtong marine optical': 2021,
                    'jiangsu hengtong optic electric': 2021,
                    'shaanxi yacheng microelectronics': 2021,
                    'shanghai aisino hangxin electronic': 2021,
                    'shanghai zuoshi control': 2021,
                    'shenzhen ruifen technology': 2021,
                    'refon technology': 2021,
                    'mingyang electric': 2021,
                    'zhongtian technology submarine cable': 2021,
                    'ztt submarine cable': 2021,
                    'keqin ket electronics': 2022,
                    'hong kong shijieta': 2022,
                    'xinnuo electronics': 2022,
                    'signo electronics': 2022,
                    'weike electronics': 2022,
                    'vico electronics': 2022,
                    'wangnianhua electronics': 2022,
                    'beijing hailanxin data': 2022,
                    'cssc electronics': 2022,
                    'sansha hailanxin data': 2022,
                    'sanya hailan huanyu marine': 2022,
                    'anhui cambricon': 2022,
                    'anzhou international group': 2022,
                    'beijing huatian haifeng': 2022,
                    'beijing machinery industry automation': 2022,
                    'beijing unistrong': 2022,
                    'beijing yinjing': 2022,
                    'cambricon technologies': 2022,
                    'cetc cloud': 2022,
                    'china electronics lais': 2022,
                    'guangdong qinzhi': 2022,
                    'hefei zhaoxin electronics': 2022,
                    'nanjing aixi information': 2022,
                    'nanjing lais cyber': 2022,
                    'nanjing lais electronic': 2022,
                    'nanjing lais information': 2022,
                    'shenzhen pengxin micro integrated': 2022,
                    'shanghai cambricon': 2022,
                    'shanghai micro electronics': 2022,
                    'shanghai suowei information': 2022,
                    'suzhou cambricon information': 2022,
                    'liyang 28th institute systems equipment': 2022,
                    'tianjin tiandy technologies': 2022,
                    'xiongan cambricon': 2022,
                    'yangtze memory': 2022,
                    'beijing zhongke xinlian': 2022,
                    'beijing nanjiang aerospace': 2023,
                    'dongguan lingkong remote': 2023,
                    'yigesiman aviation': 2023,
                    'guangzhou tianhaixiang': 2023,
                    'shanxi yigesiman': 2023,
                    'aook tech': 2023,
                    'beijing tiantai': 2023,
                    'beijing yunze': 2023,
                    'de aerospace': 2023,
                    'deyuhang tech': 2023,
                    'changsha wuyi space': 2023,
                    'beijing fourth paradigm': 2023,
                    'quanxiang international freight': 2023,
                    'aisu industrial': 2023,
                    'aisu industries': 2023,
                    'baoding giant': 2023,
                    'baoding shizitong enterprise': 2023,
                    'beijing zhengyuan chuangshi': 2023,
                    'bgi forensic': 2023,
                    'baoding kaituo precision': 2023,
                    'inspur group': 2023,
                    'loongson tech': 2023,
                    'nanjing gelunba': 2023,
                    'nanjing jiuding': 2023,
                    'shanghai shunmiao': 2023,
                    'suzhou shengke communication': 2023,
                    'suzhou shengke tech': 2023,
                    'luopu haishi dingxin electronic': 2023,
                    'moyu haishi electronic': 2023,
                    'pishan haishi yongan': 2023,
                    'urumqi haishi xinan electronic': 2023,
                    'yutian haishi meitian electronic': 2023,
                    'liwei tech': 2023,
                    'yishang network': 2023,
                    'eshang network': 2023,
                    'yongli electronic': 2023,
                    'china aviation technology': 2023,
                    'beijing yiweixun tongchuang': 2023,
                    'beijing luoluo tech': 2023,
                    'beijing ruiyuan wende': 2023,
                    'beijing tianshenghua information': 2023,
                    'beijing tianshenghua tech': 2023,
                    'beierte consulting': 2023,
                    'belltech consulting': 2023,
                    'changzhou youtaike': 2023,
                    'chengdu boyang': 2023,
                    'china tianli aviation': 2023,
                    'yiqiang international trade': 2023,
                    'xianfeng services': 2023,
                    'xanfeng services': 2023,
                    'dazhong technology': 2023,
                    'volks technology': 2023,
                    'xinxin industrial investment': 2023,
                    'outang': 2023,
                    'anshi asia pacific': 2023,
                    'ansys ap tech': 2023,
                    'shenzhen qianpu': 2023,
                    'shanghai aerospace': 2023,
                    'shanghai qingfeng tech': 2023,
                    'shanghai qingfeng technology': 2023,
                    'shanghai chaosuan': 2023,
                    'shanghai supercomputing tech': 2023,
                    'jinda electronics': 2023,
                    'general enterprise': 2023,
                    'xinjiang kehua hechang': 2023,
                    'asia pacific link': 2023,
                    'asiapac link': 2023,
                    'guilin alpha rubber': 2023,
                    'hangzhou fuyang ketuo': 2023,
                    'ruiwen international trade': 2023,
                    'shenzhen kasipu tech': 2023,
                    'lianmeng electronic tech': 2023,
                    'alliance electronics tech': 2023,
                    'alpha trade': 2023,
                    'shanghai yalian': 2023,
                    'zhongyin semiconductor': 2023,
                    'shenzhen chaaisi electronic': 2023,
                    'chengdu jingxin microwave': 2023,
                    'china shengshi international': 2023,
                    'yijing tech': 2023,
                    'gelaite electronic tech': 2023,
                    'global shell customs brokerage': 2023,
                    'huayuan shitong': 2023,
                    'jingfu circuit boards': 2023,
                    'niuwotai international trade': 2023,
                    'nuopuxun electronic tech': 2023,
                    'anshida electronics': 2023,
                    'pt tech': 2023,
                    'rongbotong semiconductor': 2023,
                    'shanghai yingzhong': 2023,
                    'shenzhen yishida': 2023,
                    'shiwabei optoelectronics': 2023,
                    'sentuo semiconductor': 2023,
                    'sento semiconductor': 2023,
                    'quanzhou nanan teyitong electronics': 2023,
                    'youchuang pcb': 2023,
                    'utron pcb': 2023,
                    'yongqi international': 2023,
                    'zeyuan tech': 2023,
                    'beijing biren tech': 2023,
                    'guangzhou biren': 2023,
                    'hangzhou biren': 2023,
                    'light cloud': 2023,
                    'guangxian cloud': 2023,
                    'moore threads': 2023,
                    'shanghai biren': 2023,
                    'chaoran semiconductor': 2023,
                    'chaoran semi': 2023,
                    'shanghai xinzhili enterprise': 2023,
                    'zhuhai biren': 2023,
                    'pride tech': 2023,
                    'shenzhen sipide industrial': 2024,
                    'shenzhen speed industrial': 2024,
                    'shihe tech': 2024,
                    'united electronics': 2024,
                    'chengdu beizhan electronics': 2024,
                    'beijing anhuaixin': 2024,
                    'jiangxi xintuo': 2024,
                    'lianzhong cluster': 2024,
                    'shenzhen jasbo': 2024,
                    'siteng heli': 2024,
                    'xian likechuangxin': 2024,
                    'aee shenzhen yidian': 2024,
                    'beijing bdstar navigation': 2024,
                    'beijing leike defense': 2024,
                    'beijing ruidakang': 2024,
                    'beijing tianhaida': 2024,
                    'beijing zhongshang dingsheng': 2024,
                    'cetc chip tech': 2024,
                    'cetc siyi tech': 2024,
                    'chengdu huaricom': 2024,
                    'chengdu zongheng automation': 2024,
                    'china electronics technology group corporation electronic equipment division': 2024,
                    'cetc electronic equipment division': 2024,
                    'csic pengli': 2024,
                    'supermap': 2024,
                    'star map': 2024,
                    'hexin xingtong': 2024,
                    'origin quantum computing': 2024,
                    'origin quantum': 2024,
                    'shenzhen yidian': 2024,
                    'suzhou telecommunication motor': 2024,
                    'taiyuan yifute equipment': 2024,
                    'united microelectronics center': 2024,
                    'xian hengda microwave': 2024,
                    'zhongke star map space': 2024}

    match = process.extractOne(entry, full_result.keys(), scorer=fuzz.partial_ratio)
    if match and match[1] >= 99:
        return full_result[match[0]]
    return None